root: true
env:
  browser: false
  es6: true
  node: true
extends: ["eslint:recommended"]
# parser: "@babel/eslint-parser"

parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  linebreak-style:
    - warn
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-unused-vars: 0
